sudo: required
language: node_js
node_js:
  - 10
env:
  global:
    - NODE_OPTIONS="--max_old_space_size=4096"
git:
  depth: 1
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libsecret-1-dev
      - xvfb
      - libx11-dev
      - libxkbfile-dev
branches:
  only:
    - master
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.1
  - export PATH=$HOME/.yarn/bin:$PATH ;
before_script:
  - yarn --version
script:
  - npm i
  - npm run compile
  - npm run lint
